mixology/drink/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from drink import views


urlpatterns = patterns('',
    url(r'^$', views.main, name='main'),
    url(r'^search/', views.search_drinks),
    url(r'^advancedsearch/', views.advanced_search),
    url(r'^init/', views.init),
    url(r'^favorites', views.favorites, name="favorites"),
    url(r'^(?P<drink_id>\d+)/vote/', views.vote),
    url(r'^(?P<drink_id>\d+)/addfav/', views.add_favorite),
    url(r'^(?P<drink_id>\d+)/removefav/', views.remove_favorite),
    url(r'^(?P<drink_id>\d+)/add-tag/', views.add_tag),
    url(r'^(?P<drink_id>\d+)/$', views.drink_view),
    )

mixology/mixology/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from mixology import views
import drink
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mixology.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^drink/', include('drink.urls', namespace='drink')),
    url(r'^login/', 'django.contrib.auth.views.login', {'template_name': 'mixology/login.html'},name="login"),
    url(r'^$', drink.views.main, name='main'),
    url(r'^search/', drink.views.advanced_search, name='search')
)

mixology/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.0/css/jasny-bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <script src="/static/js/jquery-2.1.0.min.js"></script>
    {% block head %}
    {% endblock %}
</head>
<body style="padding-top: 20px; padding-bottom: 20px;">
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Mixology</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="left"><a href="{% url 'main'%}">Main</a></li>
                    <li class="right"><a href="{% url 'search'%}">Cabinet search</a></li>

                </ul>
                <div class="nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'drink:favorites' %}">Favorites</a></li>
                        <li class="right">{{user.name}}</li>
                    {% else %}
                        <li class="right"><a href="{% url 'login'%}">Login</a></li>
                    {% endif %}
                    {% block extra_btn %}
                    {% endblock %}
            </div>
        </div>
    </nav>
</div>
{% block content %}
{% endblock %}
</body>
</html>
</html>